KS-20
Kreamish/KreamishServer pull request #20
Opened 2023-07-23 07:27 UTC by seung-woo-ryu

# 아이템 댓글, 좋아요

2023-07-23 07:28 UTC, seung-woo-ryu commented on src/main/java/com/kreamish/kream/comment/entity/Comment.java
> +    private String content;
책님 여기 원래 String value였는데 DB 예약어여서 content로 변수명 바꿨어요

2023-07-23 07:29 UTC, seung-woo-ryu commented on src/main/java/com/kreamish/kream/common/runner/TestDataRunner.java
> +        ITEM1_WITH_BRAND1_CATEGORY1_DETAIL1_AND_COMMENT_CNT_IS_2 = saveItem("item1", "subName1",
이름이 복잡해서 바꿔봐야할거 같은데 어떻게 할지 모르겠네요 ㅠㅠ
변수명 마지막에 특정 테스트와 연관되는 이름 넣는거 좋은거 같아요
COMMENT_CNT_IS_2 <- 이런거 넣어봤는데 나쁘진 않은거 같습니다

2023-07-23 07:38 UTC, seung-woo-ryu commented on src/main/java/com/kreamish/kream/common/runner/TestDataRunner.java
> +public class TestDataRunner implements ApplicationRunner {
테스트 데이터 코드 KS-24보다 KS-20(현재 보고있는)에 작성된게 많아서
KS-24 폐기하고 이걸로 같이 푸쉬할게요

2023-07-23 11:50 UTC, kangyunsik requested changes

2023-07-23 11:50 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/comment/controller/CommentController.java
> +    @PostMapping("/comment")
comments 로 변경하는게 좋지 않을까 싶습니다 !
restful api 에서 관례적으로, 복수형을 쓰는게 좋을 것 같습니다.

2023-07-23 11:50 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/comment/controller/CommentController.java
> +    @DeleteMapping("/comment/{comment-id}/member/{member-id}")
댓글은 crud 외에 다른 기능이 없을 듯 하여, 사용자 위주로 댓글보다 먼저 path variable 에서 사용하면 좋지 않을까 싶습니다. 추후 구매나 판매 입찰 등 사용자가 주체로 api를 호출하는 경우가 많을 듯 하여, /members/{member-id}/comments/{comments-id} 로 사용하는 것이 좋지 않을까 생각됩니다.

2023-07-23 11:50 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/common/runner/TestDataRunner.java
> +public class TestDataRunner implements ApplicationRunner {
네 test코드 쪽에 작성할 수 있다면 좋을 거 같습니다

2023-07-25 11:53 UTC, kangyunsik approved these changes

2023-07-25 11:53 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/member/service/MemberService.java
> +    @Transactional(readOnly = true)
서비스에 Transactional 있어서, 이 부분 제거해도 될 거 같습니다 !

2023-07-25 11:53 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/comment/controller/CommentController.java
> +    @DeleteMapping("/comment/{comment-id}/member/{member-id}")
우선 복수형 변경하고, /member/member-id 부분은 request parameter 로 빼 두었다가 추후 변경하시죠 !

2023-07-25 11:53 UTC, merged