필터 API 수정 + 코드 수정
Kreamish/KreamishServer pull request #22
Opened 2023-08-10 15:30 UTC by seung-woo-ryu

- [x] 서비스 레이어 인터페이스 추가
- [x] @${HTTP_METHOD}Mapping에 적절한 produces, consumes 옵션 설정
- [x] requestBody에 key 값이 camelCase로 통일
- [x] filter api response 포맷 수정

2023-08-10 15:33 UTC, seung-woo-ryu commented on Dockerfile
윤식 책임님 도커 안에서 빌드 돌리는게 2~3분 정도 걸렸구요
로컬에서 빌드해서 jar 파일 생성하고 걔만 copy하게끔 수정하니깐 20초 정도로 줄었습니다
그런데 push해놓고 생각해보니 CI/CD 구축하셨을텐데 Dockerfile 맘대로 수정하면 안될거 같아서 언급하고 넘어가요!

2023-08-10 15:34 UTC, seung-woo-ryu commented on Dockerfile
> +CMD java -jar kream-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
@kangyunsik  AS-IS가 2~3분 정도 걸리는데
로컬에서 빌드해서 jar 파일 생성하고 걔만 copy하게끔 수정하니깐 20초 정도로 줄었습니다
그런데 push해놓고 생각해보니 CI/CD 구축하셨을텐데 Dockerfile 맘대로 수정하면 안될거 같아서 언급하고 넘어가요!

2023-08-10 15:46 UTC, seung-woo-ryu commented
그리구 다음에 고쳐야 할 부분을 코드에 아래와 같이 주석을 남겼는데 그렇게 해도 될까요..? 
`// ToDo : ~~이유로 수정이 필요함`

2023-08-22 12:49 UTC, kangyunsik requested changes
조금만 수정 부탁드립니다 !

2023-08-22 12:49 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/itemsizes/service/ItemSizeServiceImpl.java
> +            .map(itemSizes -> ItemSizeDto.of(itemSizes))
N+1이 발생할 수 있을 것 같습니다.

2023-08-22 12:49 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/itemsizes/service/ItemSizeServiceImpl.java
> +            .map(itemSizes -> ItemSizeDto.of(itemSizes))
fetch join 이 두 번 될지 (Item, Category) 확인 해 봐야 될 것 같습니다 !

2023-08-22 12:49 UTC, kangyunsik commented on src/test/java/com/kreamish/kream/filter/facade/FilterFacadeTest.java
> +        System.out.println(drcBrandFilterResponseDto);
sout 변경 부탁드립니다 !

2023-09-03 02:52 UTC, kangyunsik approved these changes

2023-09-03 07:45 UTC, merged