Ks 25
Kreamish/KreamishServer pull request #27
Opened 2023-09-07 13:01 UTC by seung-woo-ryu

2023-09-07 13:06 UTC, seung-woo-ryu commented
@kangyunsik like -> favorites으로 해서 기능과 관련 없는 파일도 수정되었어요 Favorite 붙은 컨트롤러, 서비스, 레포지토리, 테스트만 봐주시면 돼요!

2023-09-07 14:12 UTC, kangyunsik requested changes

2023-09-07 14:12 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/favorite/dto/FavoriteCntResponseDto.java
> +public class FavoriteCntResponseDto {
getter 없이 요청 값을 정상 처리할 수 있을지 확인이 필요할 것 같습니다

2023-09-07 14:12 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/favorite/enity/Favorite.java
> +    private ItemSizes itemSizes;
LAZY 로딩을 명시해야 될 것 같습니다.
주로, ?ToOne은 기본이 EAGER여서, LAZY로 명시해둡니다.
ItemSizes 에서도 Item에 ManyToOne인데, EAGER네요. 이슈로 등록해두겠습니다 !

2023-09-08 12:10 UTC, seung-woo-ryu commented on src/main/java/com/kreamish/kream/favorite/dto/FavoriteCntResponseDto.java
> +public class FavoriteCntResponseDto {
[Jackson 라이브러리 이해](https://mommoo.tistory.com/83)

Spring Boot에서 Controller에 @ResponseBody가 붙으면 메시지 컨버터가 동작하면서 Jackson을 이용 object <-> json을 한다고 합니다. Jackson에서 제공하는 @JsonProperty를 붙이면 변환과정에서 Getter/Setter가 없어도 동작한대요!

2023-09-09 12:02 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/favorite/dto/FavoriteCntResponseDto.java
> +public class FavoriteCntResponseDto {
오호 그렇군여... 배워갑니다

2023-09-09 12:04 UTC, kangyunsik approved these changes

2023-09-09 13:00 UTC, merged