style: fix indent, tap size. feat: add category Dto. feat: add Genera…
Kreamish/KreamishServer pull request #7
Opened 2023-05-30 12:41 UTC by seung-woo-ryu

style: fix indent, tap size. feat: add category Dto. feat: add Genera…

2023-05-30 14:24 UTC, kangyunsik requested changes
수정 후 push 부탁드립니당

2023-05-30 14:24 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/dto/CategoriesDto.java
> +    List<CategoryDto> categoryDtoList;
<img width="291" alt="스크린샷 2023-05-30 오후 11 18 43" src="https://github.com/Kreamish/KreamishServer/assets/55424354/60f3dd10-debb-461e-96c7-1617f9275500">

<img width="308" alt="스크린샷 2023-05-30 오후 11 19 36" src="https://github.com/Kreamish/KreamishServer/assets/55424354/8faa902a-61ce-4939-90ac-9fcf066417b8">

```java
@JsonProperty(value = "categories")
```
사용해서 객체 이름 설정하면 좋을 것 같아요.
DTO 네이밍은 추후에 다시 얘기 하시죠!

2023-05-30 14:24 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/errors/GeneralExceptionHandler.java
> +    public ResponseEntity<ApiResult<?>> handleGeneralException(Exception e) {
wild card 대신 아래처럼 사용하면 좋을 것 같아요.

```java
public ResponseEntity<ApiResult<CategoriesDto>> getItems()
```

2023-06-01 14:25 UTC, seung-woo-ryu commented on src/main/java/com/kreamish/kream/errors/GeneralExceptionHandler.java
> +    public ResponseEntity<ApiResult<?>> handleGeneralException(Exception e) {
요거 같은 경우에 error라서 원하는 결과 Dto(CategoriesDto같은)가 들어가지 않고 에러 관련된 Dto가 들어가거나 아무것도 안 들어갈거 같아요!
=> ? 와일드 카드로 놔두던가 아니면 error response 객체 자체를 또 만들어서 그걸로 하던가 고려해봐야할거 같습니다!

2023-06-01 14:26 UTC, seung-woo-ryu commented on src/main/java/com/kreamish/kream/dto/CategoriesDto.java
> +    List<CategoryDto> categoryDtoList;
오 감사합니다! 저런 것도 생각했어야 했네요!!

2023-06-04 17:36 UTC, seung-woo-ryu commented on src/main/java/com/kreamish/kream/KreamApplication.java
>  public class KreamApplication {
@EnableJpaAuditing을 Main Class에 붙이니까 jpa repository관련 없는 단위테스트 진행할 때 마다 JPA 관련 Configuration을 진행해서 QueryDslConfiguration으로 옮겼습니다!

2023-06-04 17:40 UTC, seung-woo-ryu commented on src/test/java/com/kreamish/kream/controller/CategoryControllerTest.java
> +    void setup() {
컨트롤러만 Unit Test하게 작성했는데 통합테스트도 필요할까요?
각 레이어마다 Unit Test를 잘 작성해두면 필요없어 보이는데 궁금하네요

2023-06-13 12:02 UTC, kangyunsik commented on src/test/java/com/kreamish/kream/controller/CategoryControllerTest.java
> +    void setup() {
음, validation 체크같이 컨트롤러 쪽에서 수행하는 걸 테스트 하는 용도면 필요할 수도 있겠다고 생각되네요

2023-06-13 12:07 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/errors/GeneralExceptionHandler.java
> +    public ResponseEntity<ApiResult<?>> handleGeneralException(Exception e) {
앗 커멘트를 잘못된 위치에 달았네요... 다시 커멘트 남길게요!

2023-06-13 12:11 UTC, kangyunsik requested changes
리뷰 드립니다!

1. 제네릭 명시
2. 트랜잭셔널 어노테이션 반전

2023-06-13 12:11 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/controller/CategoryController.java
> +        return new ResponseEntity<>(ApiUtils.success(findCategories), httpStatus);
ExceptionHandler 부분에 커멘트 잘못 달았었어요...
여기 부분에선, 와일드카드 대신 제네릭 넣어도 될 것 같습니다!

2023-06-13 12:11 UTC, kangyunsik commented on src/main/java/com/kreamish/kream/service/CategoryService.java
> +        return CategoriesDto.of(categoryRepository.findAll());
이 부분 잘못 설명드렸네요 ㅠ

Service 측에 readOnly 두고, 메서드에서 그냥 트랜잭셔널 어노테이션 쓰면 좋을 것 같아요.

조회하는 메서드가 대부분이라서, 그렇게 사용하는 것이 좋다고 생각됩니다.

2023-06-13 12:45 UTC, kangyunsik approved these changes
임시 승인입니다!

2023-06-13 12:46 UTC, merged